config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/skip_profile_photo_upload', to: 'dashboard#skip_profile_photo_upload', as: :skip_profile_photo_upload

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Users Controller
  #
  # Admin only
  #
  get 'users', to: 'users#index'
  post 'users/:id/approve', to: 'users#approve_as_admin', as: :approve_as_admin
  get 'users/admin_photo_album', to: 'users#admin_photo_album', as: :admin_photo_album
  post 'users/create_admin_photo_album', to: 'users#create_admin_photo_album', as: :create_admin_photo_album
  patch 'users/update_admin_photo_album', to: 'users#update_admin_photo_album', as: :update_admin_photo_album
  delete 'users/destroy_photo_from_admin_photo_album/:image_id', to: 'users#destroy_photo_from_admin_photo_album', as: :destroy_photo_from_admin_photo_album
  get 'users/admin_family_tree', to: 'users#admin_family_tree', as: :admin_family_tree
  post 'users/create_admin_family_tree', to: 'users#create_admin_family_tree', as: :create_admin_family_tree
  delete 'users/family_tree_photo', to: 'users#destroy_family_tree_photo', as: :destroy_family_tree_photo

  #
  # End Admin Only
  #
  patch 'users/attach_avatar', to: 'users#attach_avatar', as: :attach_avatar
  get 'settings', to: 'users#settings', as: :settings
  patch 'update_settings', to: 'users#update_settings', as: :update_settings
  patch 'update_password', to: 'users#update_password', as: :update_password

  # Recipes Controller
  resources :recipes do
    post '/comments', to: 'recipe_comments#create'
    delete '/comments/:id', to: 'recipe_comments#destroy', as: :comment_destroy
  end

  # PhotoAlbums Controller
  resources :photo_albums

  # Messages Controller
  resources :messages do
    post '/comments', to: 'message_comments#create'
    delete '/comments/:id', to: 'message_comments#destroy', as: :comment_destroy
  end

  # Family Controller
  get '/family/tree', to: 'family#tree', as: :family_tree
  get '/family/bios', to: 'family#bios', as: :family_bios

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # GET /
  def index
    @user = current_user
    @photo_album = PhotoAlbum.find_by(is_admin: true, admin_type: 'home_page_carousel')
  end

  # GET dashboard/skip_profile_photo_upload
  def skip_profile_photo_upload
    session[:skipped_profile_photo_upload] = true
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_new_user_welcome_modal.html.erb
<div class="modal fade" id="welcome-modal" tabindex="-1" aria-labelledby="welcome-modal" aria-hidden="true">
  <div class="modal-dialog">
    <%= form_with model: @user, url: attach_avatar_path, method: :patch do |form| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Welcome to the Hoang Family Website!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Please upload a profile photo</p>
          <small>You can always do this later from your Settings page</small>
          
          <div class="form-group my-2">
            <div class="custom-file">
              <%= form.file_field :avatar, class: "custom-file-input", id: "customFile" %>
              <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
          </div>

        </div>
        <div class="modal-footer">
          <%= link_to "Skip, I'll do this later", skip_profile_photo_upload_path, remote: true, class: "btn btn-secondary" %>
          <%= form.submit "Upload", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= bootstrap_flash %>

<% unless @user.has_at_least_one_bio_attribute_present? %>
  <div class="alert alert-warning" role="alert">
    <div class="container">
      <div class="alert-icon">
        <i class="now-ui-icons users_single-02"></i>
      </div>
      Your bio awaits, add your information on the <%= link_to 'info tab', settings_path(tab: "settings_info") %> and <%= link_to 'social tab', settings_path(tab: "settings_social") %> so your family can see it on the <%= link_to 'Bios', family_bios_path %> page.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">
          <i class="now-ui-icons ui-1_simple-remove"></i>
        </span>
      </button>
    </div>
  </div>
<% end %>

<% if @photo_album %>
  <div id="main-site-carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% @photo_album.images.each_with_index do |image, idx| %>
        <div class="carousel-item <%= 'active' if idx == 0 %>">
          <%= image_tag(image, class: "d-block w-100") %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#main-site-carousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#main-site-carousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% else %>
  <p>If you're the Administrator for the site, please upload photos to carousel <%= link_to 'here', admin_photo_album_path %></p>
<% end %>

<%= render_upload_photo_modal(@user) %>

app/views/dashboard/skip_profile_photo_upload.js.erb
$('#welcome-modal').modal('hide');