config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/skip_profile_photo_upload', to: 'dashboard#skip_profile_photo_upload', as: :skip_profile_photo_upload

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Users Controller
  #
  # Admin only
  #
  get 'users', to: 'users#index'
  post 'users/:id/approve', to: 'users#approve_as_admin', as: :approve_as_admin
  get 'users/admin_photo_album', to: 'users#admin_photo_album', as: :admin_photo_album
  post 'users/create_admin_photo_album', to: 'users#create_admin_photo_album', as: :create_admin_photo_album
  patch 'users/update_admin_photo_album', to: 'users#update_admin_photo_album', as: :update_admin_photo_album
  delete 'users/destroy_photo_from_admin_photo_album/:image_id', to: 'users#destroy_photo_from_admin_photo_album', as: :destroy_photo_from_admin_photo_album
  get 'users/admin_family_tree', to: 'users#admin_family_tree', as: :admin_family_tree
  post 'users/create_admin_family_tree', to: 'users#create_admin_family_tree', as: :create_admin_family_tree
  delete 'users/family_tree_photo', to: 'users#destroy_family_tree_photo', as: :destroy_family_tree_photo

  #
  # End Admin Only
  #
  patch 'users/attach_avatar', to: 'users#attach_avatar', as: :attach_avatar
  get 'settings', to: 'users#settings', as: :settings
  patch 'update_settings', to: 'users#update_settings', as: :update_settings
  patch 'update_password', to: 'users#update_password', as: :update_password

  # Recipes Controller
  resources :recipes do
    post '/comments', to: 'recipe_comments#create'
    delete '/comments/:id', to: 'recipe_comments#destroy', as: :comment_destroy
  end

  # PhotoAlbums Controller
  resources :photo_albums

  # Messages Controller
  resources :messages do
    post '/comments', to: 'message_comments#create'
    delete '/comments/:id', to: 'message_comments#destroy', as: :comment_destroy
  end

  # Family Controller
  get '/family/tree', to: 'family#tree', as: :family_tree
  get '/family/bios', to: 'family#bios', as: :family_bios

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/recipe.rb
# Recipes of all kinds
# @param test_param [String] optional, test comment here
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_rich_text :ingredients
  has_rich_text :directions

  CATEGORIES = [
    'pork',
    'chicken',
    'eggs',
    'beef',
    'seafood',
    'soup',
    'vegetarian/vegan',
    'appetizers',
    'desserts',
    'noodles/pasta'
  ].freeze

  validates :name, :ingredients, :directions, :category, presence: true
  validates :serving_size, :total_cook_time, numericality: { greater_than: 0 }, allow_blank: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user

  # GET /recipes
  def index
    @recipes = Recipe.includes(:user).all
  end

  # GET /recipes/new
  def new
    @recipe = @user.recipes.new
  end

  # GET /recipes/:id
  def show
    @recipe = Recipe.includes(:comments, :user).find(params[:id])
  end

  # GET /recipes/:id/edit
  def edit
    @recipe = Recipe.find(params[:id])
    authorize! :update, @recipe
  end

  # POST /recipes
  # rubocop: disable Metrics/AbcSize
  def create
    @recipe = @user.recipes.new(recipe_params)

    if @recipe.save
      flash[:success] = "Successfully added #{@recipe.name}!"
      redirect_to recipes_path
    else
      flash[:error] = @recipe.errors.messages.values.flatten.uniq
      render :new
    end
  end
  # rubocop: enable Metrics/AbcSize

  # PATCH /recipes/:id
  # rubocop: disable Metrics/AbcSize
  def update
    @recipe = Recipe.find(params[:id])
    authorize! :update, @recipe

    if @recipe.update(recipe_params)
      flash[:success] = "Successfully updated #{@recipe.name}"
      redirect_to recipes_path
    else
      flash[:error] = @recipe.errors.messages.values.flatten.uniq
      render :edit
    end
  end
  # rubocop: enable Metrics/AbcSize

  # DELETE /recipes/:id
  def destroy
    @recipe = Recipe.find(params[:id])
    authorize! :destroy, @recipe
    @recipe.destroy

    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(
      :name,
      :ingredients,
      :directions,
      :category,
      :serving_size,
      :total_cook_time
    )
  end

  def set_user
    @user = current_user
  end
end

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, local: true do |form| %>
  <div class="form-group mb-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :ingredients %>
    <%= form.rich_text_area :ingredients, class: "form-control" %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :directions %>
    <%= form.rich_text_area :directions, class: "form-control" %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :category %>
    <%= form.select :category, Recipe::CATEGORIES, { include_blank: 'Choose one' }, class: "form-control custom-select" %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :serving_size, "Serving Size (Optional)" %>
      <%= form.text_field :serving_size, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :total_cook_time, "Total Cook Time In Minutes (Optional)" %>
      <%= form.text_field :total_cook_time, class: "form-control" %>
    </div>
  </div>

  <div class="mt-3 float-right">
    <%= link_to "Cancel", recipes_path, class: "btn btn-secondary mr-2" %>
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/_recipe_comments.html.erb
<div class="card">
  <div class="card-body">
    <div class="d-flex justify-content-start mb-3">
      <%= rounded_avatar(comment.user, 70, 70) %>
      <div class="ml-3">
        <p><strong><%= comment.user.full_name %></strong> made a post.</p>
        <h6 class="text-muted time font-weight-lighter"><%= time_ago_in_words(comment.created_at) %> ago</h6>
      </div>
    </div>
    <p class="card-text"><%= comment.comment %></p>
    <% if can? :destroy, comment %>
      <%= link_to "Delete Comment", recipe_comment_destroy_path(@recipe, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "font-weight-light text-danger", style: "font-size: 10px" %>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="row my-5">
  <div class="col-lg-2"></div>

  <div class="col-lg-8">
    <%= bootstrap_flash %>
    <h5 class="section-title h1">EDIT <%= @recipe.name.upcase %></h5>

    <%= render "form" %>
  </div>

  <div class="col-lg-2"></div>
</div>

app/views/recipes/index.html.erb
<div class="row justify-content-center my-5">
  <div class="col-lg-10">
    <%= bootstrap_flash %>
    <h5 class="section-title h1">RECIPES</h5>

    <%= link_to "Add New Recipe", new_recipe_path, class: "btn btn-primary float-right" %>

    <table class="table table-sm table-hover mt-5 datatable">
      <thead>
        <tr>
          <th scope="col">Recipe</th>
          <th scope="col">Submitted By</th>
          <th scope="col">Category</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @recipes.each do |recipe| %>
          <tr>
            <td><%= recipe.name %></td>
            <td><%= recipe.user.full_name %></td>
            <td><span class="badge badge-info"><%= recipe.category %></span></td>
            <td colspan="3">
              <%= link_to "View", recipe_path(recipe), class: "btn btn-dark" %>
              <% if can? :update, recipe %>
                <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-warning" %>
              <% end %>
              <% if can? :destroy, recipe %>
                <%= link_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="row my-5">
  <div class="col-lg-2"></div>

  <div class="col-lg-8">
    <%= bootstrap_flash %>
    <h5 class="section-title h1">ADD NEW RECIPE</h5>

    <%= render "form" %>
  </div>

  <div class="col-lg-2"></div>
</div>

app/views/recipes/show.html.erb
<div class="row my-5">
  <div class="col-lg-8">
    <%= link_to "Back to Recipes", recipes_path, class: "btn btn-link" %>
    <div class="jumbotron jumbotron-fluid text-center">
      <div class="container">
        <h1 class="display-4"><%= @recipe.name %></h1>
        <p class="text-muted">By: <%= @recipe.user.full_name %></p>
        <span class="badge badge-primary mx-2"><%= @recipe.category %></span>
        <% if @recipe.serving_size %>
          <span class="badge badge-warning mx-2">Servings: <%= @recipe.serving_size %></span>
        <% end %>
        <% if @recipe.total_cook_time %>
          <span class="badge badge-info mx-2">Total Cook Time (Minutes): <%= @recipe.total_cook_time %></span>
        <% end %>
      </div>
    </div>

    <div class="card">
      <div class="card-header bg-info">
        Ingredients
      </div>
      <div class="card-body bg-dark text-white">
        <p class="card-text">
          <%= @recipe.ingredients %>
        </p>
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header bg-info">
        Directions
      </div>
      <div class="card-body bg-dark text-white">
        <p class="card-text">
          <%= @recipe.directions %>
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 mt-3">
          <h1>Comments</h1>
          <div class="error-msg"></div>
          <%= form_with model: @recipe.comments, url: recipe_comments_path(@recipe) do |form| %>
            <%= form.hidden_field :user_id, value: @user.id %>
            <div class="form-group">
              <%= form.text_area :comment, class: "form-control", placeholder: "Add new comment here..." %>
            </div>
            <div class="text-right mb-3">
              <%= form.submit "Add", class: "btn btn-primary" %>
            </div>
          <% end %>

          <div id="recipe-comments">
            <div id="recipe-comment">
              <% @recipe.comments.order(created_at: :desc).each do |comment| %>
                <%= render partial: "recipe_comments", locals: { comment: comment } %>
              <% end %>
            </div>
          </div>
        </div>
              
      </div>
    </div>
  </div>
</div>