config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/skip_profile_photo_upload', to: 'dashboard#skip_profile_photo_upload', as: :skip_profile_photo_upload

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Users Controller
  #
  # Admin only
  #
  get 'users', to: 'users#index'
  post 'users/:id/approve', to: 'users#approve_as_admin', as: :approve_as_admin
  get 'users/admin_photo_album', to: 'users#admin_photo_album', as: :admin_photo_album
  post 'users/create_admin_photo_album', to: 'users#create_admin_photo_album', as: :create_admin_photo_album
  patch 'users/update_admin_photo_album', to: 'users#update_admin_photo_album', as: :update_admin_photo_album
  delete 'users/destroy_photo_from_admin_photo_album/:image_id', to: 'users#destroy_photo_from_admin_photo_album', as: :destroy_photo_from_admin_photo_album
  get 'users/admin_family_tree', to: 'users#admin_family_tree', as: :admin_family_tree
  post 'users/create_admin_family_tree', to: 'users#create_admin_family_tree', as: :create_admin_family_tree
  delete 'users/family_tree_photo', to: 'users#destroy_family_tree_photo', as: :destroy_family_tree_photo

  #
  # End Admin Only
  #
  patch 'users/attach_avatar', to: 'users#attach_avatar', as: :attach_avatar
  get 'settings', to: 'users#settings', as: :settings
  patch 'update_settings', to: 'users#update_settings', as: :update_settings
  patch 'update_password', to: 'users#update_password', as: :update_password

  # Recipes Controller
  resources :recipes do
    post '/comments', to: 'recipe_comments#create'
    delete '/comments/:id', to: 'recipe_comments#destroy', as: :comment_destroy
  end

  # PhotoAlbums Controller
  resources :photo_albums

  # Messages Controller
  resources :messages do
    post '/comments', to: 'message_comments#create'
    delete '/comments/:id', to: 'message_comments#destroy', as: :comment_destroy
  end

  # Family Controller
  get '/family/tree', to: 'family#tree', as: :family_tree
  get '/family/bios', to: 'family#bios', as: :family_bios

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  after_create :send_admin_mail

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :photo_albums, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_one_attached :avatar

  validates :first_name, :last_name, :email, presence: true

  attr_accessor :current_password

  scope :non_admin_approved_users, -> { where(admin: false, approved: true) }
  scope :enables_new_message_posted_notifications, -> {
    where(is_notified_when_new_message_posted: true)
  }

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    approved? ? super : :not_approved
  end

  def send_admin_mail
    AdminMailer.delay.new_user_waiting_for_approval(email)
  end

  def full_name
    [first_name, last_name].join(' ').squish
  end

  def facebook?
    facebook.present?
  end

  def instagram?
    instagram.present?
  end

  def twitter?
    twitter.present?
  end

  def linkedin?
    linkedin.present?
  end

  def has_at_least_one_bio_attribute_present?
    bio.present? || date_of_birth.present? || location.present? || occupation.present? ||
      phone_number.present? || facebook? || instagram? || twitter? || linkedin?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_allowed_render_tabs, only: [:update_settings, :update_password]
  before_action :verify_user_is_admin, only: [:admin_photo_album, :create_admin_photo_album,
                                              :admin_family_tree, :create_admin_family_tree]

  ALLOWED_RENDER_TABS = [
    'settings_general',
    'settings_change_password',
    'settings_info',
    'settings_social',
    'settings_notifications'
  ].freeze

  # GET /users
  def index
    @users = if params[:approved] == "false"
               User.where(approved: false)
             else
               User.where(approved: true)
             end
  end

  # POST /users/:id/approve
  def approve_as_admin
    @user = User.find(params[:id])
    @user.update(approved: true)

    flash[:notice] = "#{@user.full_name} has been approved."
    redirect_to users_path(approved: false)
  end

  # GET /admin_photo_album
  def admin_photo_album
    @admin_photo_album = PhotoAlbum.find_by(is_admin: true, admin_type: 'home_page_carousel')
  end

  # POST /create_admin_photo_album
  # rubocop: disable Metrics/AbcSize
  def create_admin_photo_album
    @user = current_user
    @photo_album = @user.photo_albums.new(photo_album_params.merge(name: "ADMIN PHOTO ALBUM",
                                                                   is_admin: true,
                                                                   admin_type: 'home_page_carousel'))
    if @photo_album.save
      flash[:success] = "Successfully created ADMIN PHOTO ALBUM"
      redirect_to admin_photo_album_path
    else
      flash.now[:error] = @photo_album.errors.messages.values.flatten.uniq
      render :admin_photo_album
    end
  end
  # rubocop: enable Metrics/AbcSize

  def update_admin_photo_album
    @photo_album = PhotoAlbum.find_by(is_admin: true, admin_type: 'home_page_carousel')

    if @photo_album.update(photo_album_params)
      flash[:success] = "Successfully updated #{@photo_album.name}"
      redirect_to admin_photo_album_path
    else
      flash.now[:error] = @photo_album.errors.messages.values.flatten.uniq
      render :admin_photo_album_path
    end
  end

  def destroy_photo_from_admin_photo_album
    @admin_photo_album = PhotoAlbum.find_by(is_admin: true, admin_type: 'home_page_carousel')
    @image = @admin_photo_album.images.find(params[:image_id])
    @image.purge

    redirect_to admin_photo_album_path
  end

  # GET /admin_family_tree
  def admin_family_tree
    authorize! :tree, :family
    @admin_family_tree = PhotoAlbum.find_by(is_admin: true, admin_type: 'family_tree')
  end

  # POST /create_admin_photo_album
  def create_admin_family_tree
    authorize! :tree, :family
    @user = current_user
    @family_tree = @user.photo_albums.new(photo_album_params.merge(name: "FAMILY TREE",
                                                                   is_admin: true,
                                                                   admin_type: 'family_tree'))
    if @family_tree.save
      flash[:success] = "Successfully uploaded a family tree image."
      redirect_to admin_family_tree_path
    else
      flash.now[:error] = @family_tree.errors.messages.values.flatten.uniq
      render :admin_family_tree
    end
  end

  # DELETE /family_tree_photo
  def destroy_family_tree_photo
    authorize! :tree, :family
    @family_tree_photo = PhotoAlbum.find_by(is_admin: true, admin_type: 'family_tree')
    @family_tree_photo.destroy

    redirect_to admin_family_tree_path
  end

  # PATCH /users/attach_avatar
  def attach_avatar
    current_user.update(user_params)
    redirect_to root_path
  end

  # GET /settings
  def settings
    @tab = params[:tab]
    @user = current_user

    render @tab ||= "settings_general"
  end

  # PATCH /users/update_settings
  def update_settings
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "Successfully updated settings"
      redirect_to settings_path(tab: @tab)
    else
      flash.now[:error] = @user.errors.messages.values.flatten.uniq
      render @tab ||= "settings_general"
    end
  end

  # PATCH /users/update_password
  # rubocop: disable Metrics/AbcSize
  def update_password
    @user = current_user
    unless @user.valid_password?(params[:user][:current_password])
      flash.now[:error] = "Current password is invalid"
      return render @tab
    end

    if @user.update(change_password_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      flash[:success] = "Successfully updated password."
      redirect_to settings_path(tab: @tab)
    else
      flash.now[:error] = @user.errors.messages.values.flatten.uniq
      render @tab
    end
  end
  # rubocop: enable Metrics/AbcSize

  private

  def user_params
    params.require(:user).permit(
      :avatar,
      :first_name,
      :last_name,
      :bio,
      :date_of_birth,
      :location,
      :occupation,
      :phone_number,
      :facebook,
      :instagram,
      :twitter,
      :linkedin,
      :is_notified_when_new_message_posted
    )
  end

  def change_password_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end

  def photo_album_params
    params.require(:photo_album).permit(images: [])
  end

  # Brakeman Dynamic Render issue. This should protect against a user trying to access a template
  # they shouldn't have access to.
  def verify_allowed_render_tabs
    @tab = params[:tab]

    return if ALLOWED_RENDER_TABS.include?(@tab)

    redirect_to main_app.root_url, alert: 'Invalid access'
  end

  def verify_user_is_admin
    @user = current_user

    return if @user.admin?

    redirect_to main_app.root_url, alert: 'You are not authorized to view this page. '\
                                          'Please contact your administrator.'
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def active_if_current_tab(tab_name, current_tab)
    'active' if tab_name == current_tab
  end
end

app/views/users/_settings.html.erb
<div class="container light-style flex-grow-1 container-p-y my-5">
  <%= bootstrap_flash %>

    <h4 class="font-weight-bold py-3 mb-4">
      Account settings
    </h4>

    <div class="card overflow-hidden">
      <div class="row no-gutters row-bordered row-border-light">
        <div class="col-md-3 pt-0">
          <div class="list-group list-group-flush account-settings-links">
            <%= link_to "General", settings_path(tab: "settings_general"), class: "list-group-item list-group-item-action #{active_if_current_tab('settings_general', @tab)}" %>
            <%= link_to "Change password", settings_path(tab: "settings_change_password"), class: "list-group-item list-group-item-action #{active_if_current_tab('settings_change_password', @tab)}" %>
            <%= link_to "Info", settings_path(tab: "settings_info"), class: "list-group-item list-group-item-action #{active_if_current_tab('settings_info', @tab)}" %>
            <%= link_to "Social links", settings_path(tab: "settings_social"), class: "list-group-item list-group-item-action #{active_if_current_tab('settings_social', @tab)}" %>
            <%= link_to "Notifications", settings_path(tab: "settings_notifications"), class: "list-group-item list-group-item-action #{active_if_current_tab('settings_notifications', @tab)}" %>
          </div>
        </div>
        <div class="col-md-9">
          <div class="tab-content">
            <%= render tab %>
          </div>
        </div>
      </div>
    </div>  
</div>

app/views/users/_settings_change_password_tab_form.html.erb
<%= form_with model: @user, url: update_password_path, local: true, method: :patch do |form| %>
  <%= hidden_field_tag :tab, @tab %>

  <div class="tab-pane fade active show" id="account-change-password">
    <div class="card-body pb-2">

      <div class="form-group">
        <%= form.label :current_password, class: "form-label" %>
        <%= form.password_field :current_password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :password, "New Password", class: "form-label" %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :password_confirmation, class: "form-label" %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>

    </div>
  </div>

  <div class="text-right my-3">
    <%= form.submit "Save Changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_settings_general_tab_form.html.erb
<%= form_with model: @user, url: update_settings_path, local: true, method: :patch do |form| %>
  <%= hidden_field_tag :tab, @tab %>
  <div class="tab-pane fade active show" id="account-general">

  <div class="card-body media align-items-center">
    <%= rounded_avatar(current_user, 200, 200) %>
    <div class="media-body ml-4">
      <div class="custom-file">
        <%= form.file_field :avatar, class: "custom-file-input", id: "customFile" %>
        <label class="custom-file-label" for="customFile">Upload new photo</label>
      </div>
    </div>
  </div>
  <hr class="border-light m-0">

  <div class="card-body">
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: "form-control mb-1" %>
    </div>
    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: "form-control mb-1" %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control mb-1", disabled: true %>
    </div>
  </div>

  </div>

  <div class="text-right my-3">
    <%= form.submit "Save Changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_settings_info_tab_form.html.erb
<div class="alert alert-info ml-3" role="alert">
  Fill out your info below so your family can view this on the <%= link_to 'Bios', family_bios_path %> page!
</div>

<%= form_with model: @user, url: update_settings_path, local: true, method: :patch do |form| %>
  <%= hidden_field_tag :tab, @tab %>
  <div class="tab-pane fade active show" id="account-info">
    <div class="card-body pb-2">

      <div class="form-group">
        <%= form.label :bio, class: "form-label" %>
        <%= form.text_area :bio, class: "form-control", placeholder: "Write something about yourself..." %>
      </div>
      <div class="form-group">
        <%= form.label :date_of_birth, "Birthday", class: "form-label" %>
        <div class="form-row">
          <%= form.date_select :date_of_birth, { start_year: Date.today.year - 100, end_year: Date.today.year, order: [:month, :day, :year], with_css_classes: true, prompt: true }, class: "form-control col-4" %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :location, class: "form-label" %>
        <%= form.text_field :location, class: "form-control", placeholder: "e.g. Los Angeles, CA" %>
      </div>

      <div class="form-group">
        <%= form.label :occupation, class: "form-label" %>
        <%= form.text_field :occupation, class: "form-control", placeholder: "e.g. Veterinarian" %>
      </div>

      <div class="form-group">
        <%= form.label :phone_number, class: "form-label" %>
        <%= form.text_field :phone_number, class: "form-control", placeholder: "e.g. (323) 123-4567" %>
      </div>


    </div>
  </div>

  <div class="text-right my-3">
    <%= form.submit "Save Changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_settings_notification_tab_form.html.erb
<%= form_with model: @user, url: update_settings_path, local: true, method: :patch do |form| %>
  <%= hidden_field_tag :tab, @tab %>
  <div class="tab-pane fade active show" id="account-notifications">
    <div class="card-body pb-2">
      <div class="custom-control custom-checkbox">
        <%= form.check_box :is_notified_when_new_message_posted, class: "custom-control-input" %>
        <%= form.label :is_notified_when_new_message_posted, "Email me when someone posts a new message", class: "custom-control-label" %>
      </div>
    </div>
  </div>

  <div class="text-right my-3">
    <%= form.submit "Save Changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_settings_social_tab_form.html.erb
<div class="alert alert-info ml-3" role="alert">
  Fill out your info below so your family can view this on the <%= link_to 'Bios', family_bios_path %> page!
</div>

<%= form_with model: @user, url: update_settings_path, local: true, method: :patch do |form| %>
  <%= hidden_field_tag :tab, @tab %>
  <div class="tab-pane fade active show" id="account-social-links">
    <div class="card-body pb-2">
      <div class="form-group">
        <%= form.label :facebook, class: "form-label" %>
        <%= form.text_field :facebook, class: "form-control", placeholder: "e.g. www.facebook.com/user" %>
      </div>
      <div class="form-group">
        <%= form.label :instagram, class: "form-label" %>
        <%= form.text_field :instagram, class: "form-control", placeholder: "e.g. @instagramHandle" %>
      </div>
      <div class="form-group">
        <%= form.label :twitter, class: "form-label" %>
        <%= form.text_field :twitter, class: "form-control", placeholder: "e.g. @twitterHandle" %>
      </div>
      <div class="form-group">
        <%= form.label :linkedin, "LinkedIn", class: "form-label" %>
        <%= form.text_field :linkedin, class: "form-control", placeholder: "e.g. www.linkedin.com/in/johnsmith" %>
      </div>
    </div>
  </div>

  <div class="text-right my-3">
    <%= form.submit "Save Changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/admin_family_tree.html.erb
<div class="row justify-content-center my-5">
  <div class="col-lg-10">
    <%= bootstrap_flash %>
    <h1>Family Tree Upload</h1>

    <% if @admin_family_tree %>
      <p>This image is displayed on the <%= link_to 'Family tree page', family_tree_path %>.</p>
      <% @admin_family_tree.images.each do |image| %>
        <%= image_tag(image, class: "img-fluid") %>
        <%= link_to 'Delete Image', destroy_family_tree_photo_path, method: :delete %>
      <% end %>
    <% else %>
      <p>No family tree photo uploaded. Please upload a photo below.</p>
      <%= form_with model: @user.photo_albums.new, url: create_admin_family_tree_path, local: true do |form| %>
        <div class="form-group mb-4">
          <div class="custom-file">
            <%= form.file_field :images, multiple: true, direct_upload: true, class: "custom-file-input", id: "customFile" %>
            <label class="custom-file-label" for="customFile">Upload Photo</label>
            <small class="text-muted">
              You can select multiple photos from your computer by selecting the Shift key (Windows) or Command key (Mac)
            </small>
          </div>
        </div>

        <div class="mt-3 float-right">
          <%= link_to "Cancel", root_path, class: "btn btn-secondary mr-2" %>
          <%= form.submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/admin_photo_album.html.erb
<div class="row justify-content-center my-5">
  <div class="col-lg-10">
    <%= bootstrap_flash %>
    <h1>Admin Photo Album</h1>
    <p>These images will be displayed on the Carousel on the <%= link_to 'Homepage', root_path %>.</p>

    <% if @admin_photo_album %>
      <section id="gallery" class="gallery mb-5">
        <div class="container">
          <div class="row gallery-container">
            <% @admin_photo_album.images.each do |image| %>
              <div class="col-lg-4 col-md-6 gallery-item">
                <div class="gallery-wrap">
                  <%= image_tag(image, class: "img-fluid") %>
                  <%= link_to 'Delete Image', destroy_photo_from_admin_photo_album_path(image), method: :delete %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </section>

      <hr>

      <%= form_with model: @admin_photo_album, url: update_admin_photo_album_path, local: true do |form| %>
        <div class="form-group mb-4">
          <div class="custom-file">
            <%= form.file_field :images, multiple: true, direct_upload: true, class: "custom-file-input", id: "customFile" %>
            <label class="custom-file-label" for="customFile">Upload More Photo. Select multiple.</label>
          </div>
        </div>

        <div class="mt-3 text-right">
          <%= form.submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>

    <% else %>
      <%= form_with model: @user.photo_albums.new, url: create_admin_photo_album_path, local: true do |form| %>
        <div class="form-group mb-4">
          <div class="custom-file">
            <%= form.file_field :images, multiple: true, direct_upload: true, class: "custom-file-input", id: "customFile" %>
            <label class="custom-file-label" for="customFile">Upload Multiple Photos</label>
            <small class="text-muted">
              You can select multiple photos from your computer by selecting the Shift key (Windows) or Command key (Mac)
            </small>
          </div>
        </div>

        <div class="mt-3 float-right">
          <%= link_to "Cancel", root_path, class: "btn btn-secondary mr-2" %>
          <%= form.submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row my-5">
  <div class="col-lg-2"></div>

  <div class="col-lg-8">
    <h1 class="text-center">Users</h1>

    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to "Unapproved", users_path(approved: false), class: "nav-link #{params[:approved] == 'false' ? 'active' : ''}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Approved", users_path(approved: true), class: "nav-link #{params[:approved] == 'true' ? 'active' : ''}" %>
      </li>
    </ul>

    <table class="table table-striped mt-5">
      <thead>
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Email</th>
          <th scope="col">Sign up date</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.created_at %></td>
            <% if params[:approved] == 'false' %>
              <td><%= link_to "Approve User", approve_as_admin_path(user.id), method: :post, class: "btn btn-warning" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-lg-2"></div>
</div>

app/views/users/settings_change_password.html.erb
<%= render partial: "settings", locals: { tab: "settings_change_password_tab_form" } %>

app/views/users/settings_general.html.erb
<%= render partial: "settings", locals: { tab: "settings_general_tab_form" } %>

app/views/users/settings_info.html.erb
<%= render partial: "settings", locals: { tab: "settings_info_tab_form" } %>

app/views/users/settings_notifications.html.erb
<%= render partial: "settings", locals: { tab: "settings_notification_tab_form" } %>

app/views/users/settings_social.html.erb
<%= render partial: "settings", locals: { tab: "settings_social_tab_form" } %>