config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/skip_profile_photo_upload', to: 'dashboard#skip_profile_photo_upload', as: :skip_profile_photo_upload

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Users Controller
  #
  # Admin only
  #
  get 'users', to: 'users#index'
  post 'users/:id/approve', to: 'users#approve_as_admin', as: :approve_as_admin
  get 'users/admin_photo_album', to: 'users#admin_photo_album', as: :admin_photo_album
  post 'users/create_admin_photo_album', to: 'users#create_admin_photo_album', as: :create_admin_photo_album
  patch 'users/update_admin_photo_album', to: 'users#update_admin_photo_album', as: :update_admin_photo_album
  delete 'users/destroy_photo_from_admin_photo_album/:image_id', to: 'users#destroy_photo_from_admin_photo_album', as: :destroy_photo_from_admin_photo_album
  get 'users/admin_family_tree', to: 'users#admin_family_tree', as: :admin_family_tree
  post 'users/create_admin_family_tree', to: 'users#create_admin_family_tree', as: :create_admin_family_tree
  delete 'users/family_tree_photo', to: 'users#destroy_family_tree_photo', as: :destroy_family_tree_photo

  #
  # End Admin Only
  #
  patch 'users/attach_avatar', to: 'users#attach_avatar', as: :attach_avatar
  get 'settings', to: 'users#settings', as: :settings
  patch 'update_settings', to: 'users#update_settings', as: :update_settings
  patch 'update_password', to: 'users#update_password', as: :update_password

  # Recipes Controller
  resources :recipes do
    post '/comments', to: 'recipe_comments#create'
    delete '/comments/:id', to: 'recipe_comments#destroy', as: :comment_destroy
  end

  # PhotoAlbums Controller
  resources :photo_albums

  # Messages Controller
  resources :messages do
    post '/comments', to: 'message_comments#create'
    delete '/comments/:id', to: 'message_comments#destroy', as: :comment_destroy
  end

  # Family Controller
  get '/family/tree', to: 'family#tree', as: :family_tree
  get '/family/bios', to: 'family#bios', as: :family_bios

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container">
    <%= link_to HoangFamilySite::Application::APP_NAME, root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            About Us
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Family Tree", family_tree_path, class: "dropdown-item" %>
            <%= link_to "Bios", family_bios_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Our History</a>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Recipes", recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Photos", photo_albums_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", messages_path, class: "nav-link" %>
        </li>
        <% if current_user&.admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Users", users_path(approved: false), class: "dropdown-item" %>
              <%= link_to "Admin Photos", admin_photo_album_path, class: "dropdown-item" %>
              <%= link_to "Family Tree", admin_family_tree_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>

      <% if current_user %>
        <div class="d-flex justify-content-between ml-auto">
          <div class="mt-2"><%= rounded_avatar(current_user, 40, 40) %></div>
          <div class="btn-group ml-3">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.full_name %>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to "Settings", settings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>HoangFamilySite</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="turbolinks-cache-control" content="no-cache">
		<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js" type="text/javascript"></script>		
	</head>

	<body class="<%= controller.controller_name %>"
        data-controller="<%= controller.controller_path %>"
        data-action="<%= controller.action_name %>">
    <% if current_user %>
			<%= render partial: 'layouts/nav' %>
		<% end %>
		<div class="container-fluid my-5">
			<%= yield %>
		</div>

		<footer id="footer" class="footer mt-5 bg-default position-absolute w-100">
		  <div class="container">
		    <h3><%= HoangFamilySite::Application::APP_NAME %></h3>
		    <div class="copyright">
		      &copy; Copyright <strong><span><%= Date.today.year %></span></strong>. All Rights Reserved
		    </div>
		    <div class="credits">
		      <!-- All the links in the footer should remain intact. -->
		      <!-- You can delete the links only if you purchased the pro version. -->
		      <!-- Licensing information: https://bootstrapmade.com/license/ -->
		      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/family-multipurpose-html-bootstrap-template-free/ -->
		      Designed by <a href="https://www.creative-tim.com/product/now-ui-kit">Now UI Kit/Creative-Tim</a>
		    </div>
		  </div>
		</footer>
	</body>
</html>

app/views/layouts/bootstrap-mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag "application-mailer", media: "all" %>
  </head>
  <body class="bg-light">
    <%= yield %>
  </body>
</html>